### ISSUE TITLE
How to get/build the cli tool

### ISSUE THREAD

**Issue by stbischof** [Nasdanika/core#1]
I want do use the cli command for generating an ecore doc using cli. But i cant find a release of the cli tool or an doc hot to build this.

**Comment by pvlasov** [comment]
Hi Stefan,

Nasdanika CLI is part of Nasdanika Tool Suite - ``nsd.exe``. You can download the tool suite here - https://www.nasdanika.org/builds/develop/index.html

The process of generation ecore HTML documentation is two-step:

* First you generate vinci models from ecore models.
* Second you generate HTML site from the vinci files.

Both steps can be performed from CLI/Maven and in the Nasdanika Tool Suite IDE 

# 1. Generate vinci models

## Nasdanika Tool Suite IDE

This is Nasdanika CLI launch configuration screenshot:

![launch configuration](https://nasdanika.org/downloads/generate-ecore-documentation-launch-configuration.png)

You need to select "Run an application" ``org.nasdanika.cli.app``.

And then enter arguments similar to as shown below:

```
-os ${target.os} -ws ${target.ws} -arch ${target.arch} -nl ${target.nl} -consoleLog
vinci generate documentation ecore -J
-p C:\_temp\gen-output\ecore-doc-model-progress.txt
-o C:\Users\Pavel\git\release\tool-suite\doc\generated\ecore-doc
urn:org.nasdanika.ncore
urn:org.nasdanika.party
urn:org.nasdanika.engineering
urn:org.nasdanika.vinci.html
urn:org.nasdanika.vinci.bootstrap
urn:org.nasdanika.vinci.app
urn:org.nasdanika.vinci.components
urn:org.nasdanika.codegen
urn:org.nasdanika.codegen.java
```

The above command generates  several ``*.vinci`` files in ``C:\Users\Pavel\git\release\tool-suite\doc\generated\ecore-doc`` output directory.

## Command Line/Maven

You can find how to generate documentation in Maven [here](https://github.com/Nasdanika/release/blob/master/tool-suite/doc/pom-generate-doc.xml#L140). Please note that the models for which documentation is generated were installed into the Eclipse product by [p2 director](https://help.eclipse.org/2020-12/topic/org.eclipse.platform.doc.isv/guide/p2_director.html?resultof=%22%70%32%22%20%22%64%69%72%65%63%74%6f%72%22%20) [earlier in the build](https://github.com/Nasdanika/release/blob/master/tool-suite/doc/pom-generate-doc.xml#L35) and as such they are available to the generator by NS URI's. 

# 2. Generate HTML site

To generate a site you would need a "master" model which references the generated models. 
In case of [Nasdanika documentation](https://www.nasdanika.org/builds/develop/doc/index.html) there the [root model](https://github.com/Nasdanika/release/blob/master/tool-suite/doc/models/documentation.vinci) references [ecore model](https://github.com/Nasdanika/release/blob/master/tool-suite/doc/models/ecore.vinci), which in turn references the generated models.

## Nasdanika Tool Suite IDE

In the IDE you open the master model, right-click on the root node and select "Generate > Application". A site will be generated in the same folder as the model with the the same name as the model resource without ``.vinci`` extension.

![generate application](https://nasdanika.org/downloads/generate-application.png)

You can also create a copy of the CLI launch configuration and change the arguments to [generate site](https://www.nasdanika.org/builds/develop/doc/reference/cli/nsd/vinci/generate/application.html)

## Command Line/Maven

This shows how to generate application (site) from Maven: https://github.com/Nasdanika/release/blob/master/tool-suite/doc/pom-generate-doc.xml#L243



Please let me know if I've answered your question so I can close the issue.

**Comment by stbischof** [comment]
thank you
